CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(32)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 目前一個帳號一個角色；之後要支援多角色時移除 account_id 的 UNIQUE。
CREATE TABLE player_character (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT      NOT NULL UNIQUE REFERENCES account (id),
    name       VARCHAR(32) NOT NULL UNIQUE,
    zone_id    VARCHAR(64) NOT NULL,
    pos_x      REAL        NOT NULL,
    pos_z      REAL        NOT NULL
);
