-- 角色身上的物品。每次存檔整份重寫（最多 20 筆），sort_order 保留背包順序。
CREATE TABLE character_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT      NOT NULL REFERENCES player_character (id),
    template_id  VARCHAR(64) NOT NULL,
    quantity     INTEGER     NOT NULL,
    equipped     BOOLEAN     NOT NULL,
    sort_order   INTEGER     NOT NULL
);

CREATE INDEX character_item_character_idx ON character_item (character_id);
