-- 角色的任務進度。每次存檔整份重寫。
CREATE TABLE character_quest (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT      NOT NULL REFERENCES player_character (id),
    quest_id     VARCHAR(64) NOT NULL,
    completed    BOOLEAN     NOT NULL,
    progress     VARCHAR(64) NOT NULL
);

CREATE INDEX character_quest_character_idx ON character_quest (character_id);
