-- 內力：-1 代表「滿」，新角色與舊資料進入遊戲時會補滿
ALTER TABLE player_character ADD COLUMN mp INTEGER NOT NULL DEFAULT -1;

-- 學會的技能
CREATE TABLE character_skill (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT      NOT NULL REFERENCES player_character (id),
    skill_id     VARCHAR(64) NOT NULL
);

CREATE INDEX character_skill_character_idx ON character_skill (character_id);
